{% set name = "darker" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c63cbfcf707987bc5cb3da30eaf5f2348aabc03f96b7b69bc31a34e96d8f2b8a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - darker = darker.__main__:main

requirements:
  host:
    - python  >=3.6
    - pip
  run:
    - python  >=3.6
    - black  >=21.5b1,<=21.8b0
    - toml
    - typing-extensions
    - dataclasses
  run_constrained:
    - isort  >=5.0.1

test:
  imports:
    - darker
  requires:
    - pip
    - black  >=21.7b1
    - isort
  commands:
    - pip check
    - darker --help


about:
  home: https://github.com/akaihola/darker
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Apply black reformatting to Python files only in regions changed since a given commit
  dev_url: https://github.com/akaihola/darker

extra:
  recipe-maintainers:
    - akaihola
    - martinRenou
