{% set name = "darker" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a6e6a682c0604e76fe9aec7650e96a944f517563c69b28fcc076db9d957d98ea

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - darker = darker.__main__:main

requirements:
  host:
    - python  >=3.8
    - pip
  run:
    - python  >=3.8
    - black  >=22.3.0
    - darkgraylib  >=1.2.0,<1.3.dev0
    - graylint  >=1.1.1,<1.2.dev0
    - toml   >=0.10.0
  run_constrained:
    - flynt  >=0.76
    - isort    >=5.0.1
    - Pygments >=2.4.0

test:
  imports:
    - darker
  requires:
    - pip
    - black  >=22.3.0
    - darkgraylib  >=1.2.0,<1.3.dev0
    - graylint  >=1.1.1,<1.2.dev0
    - isort  >=5.0.1
  commands:
    - pip check
    - darker --help


about:
  home: https://github.com/akaihola/darker
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Apply black reformatting to Python files only in regions changed since a given commit
  dev_url: https://github.com/akaihola/darker

extra:
  recipe-maintainers:
    - akaihola
    - martinRenou
